version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_auth_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: newOrder
      POSTGRES_DB: blue_monday
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
